### ISSUE TITLE
eq

### ISSUE THREAD

**Issue by ubcent** [IvanBalakirev/geekB#2]
[L68](https://github.com/IvanBalakirev/geekB/blob/master/jQuery/tabs.html#L68) лучше использовать eq

**Comment by IvanBalakirev** [comment]
Я когда писал, что-то не вспомнил про eq, а чем лучше использовать именно eq?

**Comment by ubcent** [comment]
Эстетичнее. Нужно стараться писать самым логичным образом, чтобы взглянул и сразу все понятно.

**Comment by IvanBalakirev** [comment]
Ок)
